using System.Diagnostics;
using TrackPoint.Data;
using TrackPoint.Models;

namespace TrackPoint.Services
{
    public class TransferLogService
    {
        private readonly ApplicationDbContext _context;

        public TransferLogService(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task TransferLogAsync(int assetId, string borrowerId, string assetStatus, Enum eventType, DateTime transferDate)
        {
            var asset = _context.Asset.FirstOrDefault(a => a.AssetId == assetId);
            var tLogEntry = new TransferLog
            {
                AssetId = assetId,
                BorrowerId = borrowerId,
                OldStatus = asset.AssetStatus,
                NewStatus = assetStatus, // TODO: Should be an enum
                eventType = (Enums.eventType)eventType, // TODO: Is this cast really necessary?
                TransferDate = transferDate
            };
            await _context.TransferLog.Add(tLogEntry); // Stage the changes
            //await _context.SaveChangesAsync(); // DO NOT DO THIS, only save changes in the controller. Not sure why this was autogenerated, will be removed soon.
        }
    }
}
